// Code generated by the Encore 1.49.3 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly agents: agents.ServiceClient
    public readonly ai: ai.ServiceClient
    public readonly auth: auth.ServiceClient
    public readonly collaboration: collaboration.ServiceClient
    public readonly deployment: deployment.ServiceClient
    public readonly execution: execution.ServiceClient
    public readonly files: files.ServiceClient
    public readonly projects: projects.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.agents = new agents.ServiceClient(base)
        this.ai = new ai.ServiceClient(base)
        this.auth = new auth.ServiceClient(base)
        this.collaboration = new collaboration.ServiceClient(base)
        this.deployment = new deployment.ServiceClient(base)
        this.execution = new execution.ServiceClient(base)
        this.files = new files.ServiceClient(base)
        this.projects = new projects.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * Import the auth handler to be able to derive the auth type
 */
import type { auth as auth_auth } from "~backend/auth/auth";

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: RequestType<typeof auth_auth> | AuthDataGenerator
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { health as api_agents_health_health } from "~backend/agents/health";
import { orchestrate as api_agents_orchestrate_orchestrate } from "~backend/agents/orchestrate";
import {
    createSession as api_agents_orchestrator_createSession,
    getSession as api_agents_orchestrator_getSession,
    getTasks as api_agents_orchestrator_getTasks,
    listAgents as api_agents_orchestrator_listAgents,
    listSessions as api_agents_orchestrator_listSessions
} from "~backend/agents/orchestrator";
import {
    getStatus as api_agents_status_getStatus,
    listOrchestrations as api_agents_status_listOrchestrations
} from "~backend/agents/status";

export namespace agents {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createSession = this.createSession.bind(this)
            this.getSession = this.getSession.bind(this)
            this.getStatus = this.getStatus.bind(this)
            this.getTasks = this.getTasks.bind(this)
            this.health = this.health.bind(this)
            this.listAgents = this.listAgents.bind(this)
            this.listOrchestrations = this.listOrchestrations.bind(this)
            this.listSessions = this.listSessions.bind(this)
            this.orchestrate = this.orchestrate.bind(this)
        }

        /**
         * Creates a new agent session.
         */
        public async createSession(params: RequestType<typeof api_agents_orchestrator_createSession>): Promise<ResponseType<typeof api_agents_orchestrator_createSession>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/agents/sessions`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agents_orchestrator_createSession>
        }

        /**
         * Gets a specific session by ID.
         */
        public async getSession(params: { id: string }): Promise<ResponseType<typeof api_agents_orchestrator_getSession>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/agents/sessions/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agents_orchestrator_getSession>
        }

        /**
         * Gets the current status of a project orchestration.
         */
        public async getStatus(params: { orchestrationId: string }): Promise<ResponseType<typeof api_agents_status_getStatus>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/agents/status/${encodeURIComponent(params.orchestrationId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agents_status_getStatus>
        }

        /**
         * Gets tasks for a session.
         */
        public async getTasks(params: { sessionId: string }): Promise<ResponseType<typeof api_agents_orchestrator_getTasks>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/agents/sessions/${encodeURIComponent(params.sessionId)}/tasks`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agents_orchestrator_getTasks>
        }

        public async health(): Promise<ResponseType<typeof api_agents_health_health>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/health`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agents_health_health>
        }

        /**
         * Lists available agents.
         */
        public async listAgents(): Promise<ResponseType<typeof api_agents_orchestrator_listAgents>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/agents/list`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agents_orchestrator_listAgents>
        }

        /**
         * Lists all orchestrations for a project.
         */
        public async listOrchestrations(params: { projectId: string }): Promise<ResponseType<typeof api_agents_status_listOrchestrations>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/agents/orchestrations/${encodeURIComponent(params.projectId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agents_status_listOrchestrations>
        }

        /**
         * Lists all sessions for a project.
         */
        public async listSessions(params: { projectId: string }): Promise<ResponseType<typeof api_agents_orchestrator_listSessions>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/agents/sessions/project/${encodeURIComponent(params.projectId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agents_orchestrator_listSessions>
        }

        /**
         * Orchestrates the complete project generation using the Myco agent system.
         */
        public async orchestrate(params: RequestType<typeof api_agents_orchestrate_orchestrate>): Promise<ResponseType<typeof api_agents_orchestrate_orchestrate>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/agents/orchestrate`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_agents_orchestrate_orchestrate>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    debug as api_ai_generate_debug,
    explainCode as api_ai_generate_explainCode,
    generate as api_ai_generate_generate,
    generateCode as api_ai_generate_generateCode
} from "~backend/ai/generate";
import { health as api_ai_health_health } from "~backend/ai/health";

export namespace ai {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.debug = this.debug.bind(this)
            this.explainCode = this.explainCode.bind(this)
            this.generate = this.generate.bind(this)
            this.generateCode = this.generateCode.bind(this)
            this.health = this.health.bind(this)
        }

        /**
         * Debugs code and suggests fixes.
         */
        public async debug(params: RequestType<typeof api_ai_generate_debug>): Promise<ResponseType<typeof api_ai_generate_debug>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/debug`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_generate_debug>
        }

        /**
         * Explains code functionality and suggests improvements.
         */
        public async explainCode(params: RequestType<typeof api_ai_generate_explainCode>): Promise<ResponseType<typeof api_ai_generate_explainCode>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/explain`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_generate_explainCode>
        }

        /**
         * General AI text generation.
         */
        public async generate(params: RequestType<typeof api_ai_generate_generate>): Promise<ResponseType<typeof api_ai_generate_generate>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/generate`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_generate_generate>
        }

        /**
         * Generates complete code projects based on description.
         */
        public async generateCode(params: RequestType<typeof api_ai_generate_generateCode>): Promise<ResponseType<typeof api_ai_generate_generateCode>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/generate-code`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_generate_generateCode>
        }

        public async health(): Promise<ResponseType<typeof api_ai_health_health>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/health`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_health_health>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { health as api_auth_health_health } from "~backend/auth/health";
import { getUserInfo as api_auth_user_getUserInfo } from "~backend/auth/user";

export namespace auth {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getUserInfo = this.getUserInfo.bind(this)
            this.health = this.health.bind(this)
        }

        /**
         * Gets the current user's information.
         */
        public async getUserInfo(): Promise<ResponseType<typeof api_auth_user_getUserInfo>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/user/me`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_user_getUserInfo>
        }

        public async health(): Promise<ResponseType<typeof api_auth_health_health>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/health`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_auth_health_health>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { joinRoom as api_collaboration_room_joinRoom } from "~backend/collaboration/room";

export namespace collaboration {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.joinRoom = this.joinRoom.bind(this)
        }

        /**
         * Real-time collaboration room for a project.
         */
        public async joinRoom(): Promise<StreamInOut<StreamRequest<typeof api_collaboration_room_joinRoom>, StreamResponse<typeof api_collaboration_room_joinRoom>>> {
            return await this.baseClient.createStreamInOut(`/collaboration/rooms/${encodeURIComponent(params.projectId)}`)
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    createDeployment as api_deployment_environments_createDeployment,
    getDeployment as api_deployment_environments_getDeployment,
    getProviders as api_deployment_environments_getProviders,
    listDeployments as api_deployment_environments_listDeployments
} from "~backend/deployment/environments";

export namespace deployment {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createDeployment = this.createDeployment.bind(this)
            this.getDeployment = this.getDeployment.bind(this)
            this.getProviders = this.getProviders.bind(this)
            this.listDeployments = this.listDeployments.bind(this)
        }

        /**
         * Creates a new deployment for a project.
         */
        public async createDeployment(params: RequestType<typeof api_deployment_environments_createDeployment>): Promise<ResponseType<typeof api_deployment_environments_createDeployment>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/deployment/deploy`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployment_environments_createDeployment>
        }

        /**
         * Gets a deployment by ID.
         */
        public async getDeployment(params: { id: string }): Promise<ResponseType<typeof api_deployment_environments_getDeployment>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/deployment/deployments/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployment_environments_getDeployment>
        }

        /**
         * Lists all available deployment providers.
         */
        public async getProviders(): Promise<ResponseType<typeof api_deployment_environments_getProviders>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/deployment/providers`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployment_environments_getProviders>
        }

        /**
         * Lists all deployments for a project.
         */
        public async listDeployments(params: { projectId: string }): Promise<ResponseType<typeof api_deployment_environments_listDeployments>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/deployment/deployments/project/${encodeURIComponent(params.projectId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_deployment_environments_listDeployments>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    createEnvironment as api_execution_environments_createEnvironment,
    executeCodeInEnvironment as api_execution_environments_executeCodeInEnvironment,
    getEnvironment as api_execution_environments_getEnvironment,
    listEnvironments as api_execution_environments_listEnvironments
} from "~backend/execution/environments";
import {
    cancelExecution as api_execution_execute_cancelExecution,
    execute as api_execution_execute_execute,
    getExecution as api_execution_execute_getExecution,
    getExecutionHealth as api_execution_execute_getExecutionHealth,
    getExecutionLogs as api_execution_execute_getExecutionLogs,
    getExecutionMetrics as api_execution_execute_getExecutionMetrics,
    getExecutionStatus as api_execution_execute_getExecutionStatus,
    getSupportedLanguages as api_execution_execute_getSupportedLanguages
} from "~backend/execution/execute";

export namespace execution {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.cancelExecution = this.cancelExecution.bind(this)
            this.createEnvironment = this.createEnvironment.bind(this)
            this.execute = this.execute.bind(this)
            this.executeCodeInEnvironment = this.executeCodeInEnvironment.bind(this)
            this.getEnvironment = this.getEnvironment.bind(this)
            this.getExecution = this.getExecution.bind(this)
            this.getExecutionHealth = this.getExecutionHealth.bind(this)
            this.getExecutionLogs = this.getExecutionLogs.bind(this)
            this.getExecutionMetrics = this.getExecutionMetrics.bind(this)
            this.getExecutionStatus = this.getExecutionStatus.bind(this)
            this.getSupportedLanguages = this.getSupportedLanguages.bind(this)
            this.listEnvironments = this.listEnvironments.bind(this)
        }

        public async cancelExecution(params: { executionId: string }): Promise<ResponseType<typeof api_execution_execute_cancelExecution>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/execution/${encodeURIComponent(params.executionId)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_execution_execute_cancelExecution>
        }

        /**
         * Creates a new execution environment for a project.
         */
        public async createEnvironment(params: RequestType<typeof api_execution_environments_createEnvironment>): Promise<ResponseType<typeof api_execution_environments_createEnvironment>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/execution/environments`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_execution_environments_createEnvironment>
        }

        public async execute(params: RequestType<typeof api_execution_execute_execute>): Promise<ResponseType<typeof api_execution_execute_execute>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/execution/execute`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_execution_execute_execute>
        }

        /**
         * Executes code in a sandboxed environment.
         */
        public async executeCodeInEnvironment(params: RequestType<typeof api_execution_environments_executeCodeInEnvironment>): Promise<ResponseType<typeof api_execution_environments_executeCodeInEnvironment>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/execution/environments/execute`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_execution_environments_executeCodeInEnvironment>
        }

        /**
         * Gets an execution environment by ID.
         */
        public async getEnvironment(params: { id: string }): Promise<ResponseType<typeof api_execution_environments_getEnvironment>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/execution/environments/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_execution_environments_getEnvironment>
        }

        public async getExecution(params: { executionId: string }): Promise<ResponseType<typeof api_execution_execute_getExecution>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/execution/${encodeURIComponent(params.executionId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_execution_execute_getExecution>
        }

        public async getExecutionHealth(): Promise<ResponseType<typeof api_execution_execute_getExecutionHealth>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/execution/health`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_execution_execute_getExecutionHealth>
        }

        public async getExecutionLogs(params: { executionId: string }): Promise<ResponseType<typeof api_execution_execute_getExecutionLogs>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/execution/${encodeURIComponent(params.executionId)}/logs`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_execution_execute_getExecutionLogs>
        }

        public async getExecutionMetrics(): Promise<ResponseType<typeof api_execution_execute_getExecutionMetrics>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/execution/metrics`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_execution_execute_getExecutionMetrics>
        }

        public async getExecutionStatus(params: { executionId: string }): Promise<ResponseType<typeof api_execution_execute_getExecutionStatus>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/execution/${encodeURIComponent(params.executionId)}/status`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_execution_execute_getExecutionStatus>
        }

        public async getSupportedLanguages(): Promise<ResponseType<typeof api_execution_execute_getSupportedLanguages>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/execution/languages`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_execution_execute_getSupportedLanguages>
        }

        /**
         * Lists all environments for a project.
         */
        public async listEnvironments(params: { projectId: string }): Promise<ResponseType<typeof api_execution_environments_listEnvironments>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/execution/environments/project/${encodeURIComponent(params.projectId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_execution_environments_listEnvironments>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createDirectory as api_files_create_directory_createDirectory } from "~backend/files/create_directory";
import { deleteFile as api_files_delete_deleteFile } from "~backend/files/delete";
import { get as api_files_get_get } from "~backend/files/get";
import { health as api_files_health_health } from "~backend/files/health";
import { list as api_files_list_list } from "~backend/files/list";
import { save as api_files_save_save } from "~backend/files/save";
import { listTemplates as api_files_templates_listTemplates } from "~backend/files/templates";

export namespace files {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createDirectory = this.createDirectory.bind(this)
            this.deleteFile = this.deleteFile.bind(this)
            this.get = this.get.bind(this)
            this.health = this.health.bind(this)
            this.list = this.list.bind(this)
            this.listTemplates = this.listTemplates.bind(this)
            this.save = this.save.bind(this)
        }

        /**
         * Creates a new directory.
         */
        public async createDirectory(params: RequestType<typeof api_files_create_directory_createDirectory>): Promise<ResponseType<typeof api_files_create_directory_createDirectory>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/files/directory`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_files_create_directory_createDirectory>
        }

        /**
         * Deletes a file or directory.
         */
        public async deleteFile(params: { id: string }): Promise<ResponseType<typeof api_files_delete_deleteFile>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/files/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_files_delete_deleteFile>
        }

        /**
         * Gets a specific file by ID.
         */
        public async get(params: { id: string }): Promise<ResponseType<typeof api_files_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/files/file/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_files_get_get>
        }

        public async health(): Promise<ResponseType<typeof api_files_health_health>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/health`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_files_health_health>
        }

        /**
         * Lists all files in a project as a tree structure.
         */
        public async list(params: { projectId: string }): Promise<ResponseType<typeof api_files_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/files/${encodeURIComponent(params.projectId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_files_list_list>
        }

        /**
         * Lists all available project templates.
         */
        public async listTemplates(): Promise<ResponseType<typeof api_files_templates_listTemplates>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/files/templates`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_files_templates_listTemplates>
        }

        /**
         * Saves or updates a file.
         */
        public async save(params: RequestType<typeof api_files_save_save>): Promise<ResponseType<typeof api_files_save_save>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/files/save`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_files_save_save>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_projects_create_create } from "~backend/projects/create";
import { deleteProject as api_projects_delete_deleteProject } from "~backend/projects/delete";
import { get as api_projects_get_get } from "~backend/projects/get";
import { health as api_projects_health_health } from "~backend/projects/health";
import { list as api_projects_list_list } from "~backend/projects/list";
import { update as api_projects_update_update } from "~backend/projects/update";

export namespace projects {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.deleteProject = this.deleteProject.bind(this)
            this.get = this.get.bind(this)
            this.health = this.health.bind(this)
            this.list = this.list.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Creates a new project.
         */
        public async create(params: RequestType<typeof api_projects_create_create>): Promise<ResponseType<typeof api_projects_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_projects_create_create>
        }

        /**
         * Deletes a project and all associated files.
         */
        public async deleteProject(params: { id: string }): Promise<ResponseType<typeof api_projects_delete_deleteProject>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_projects_delete_deleteProject>
        }

        /**
         * Gets a specific project by ID.
         */
        public async get(params: { id: string }): Promise<ResponseType<typeof api_projects_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_projects_get_get>
        }

        public async health(): Promise<ResponseType<typeof api_projects_health_health>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/health`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_projects_health_health>
        }

        /**
         * Lists all projects for the authenticated user.
         */
        public async list(): Promise<ResponseType<typeof api_projects_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_projects_list_list>
        }

        /**
         * Updates a project.
         */
        public async update(params: RequestType<typeof api_projects_update_update>): Promise<ResponseType<typeof api_projects_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                deployUrl:     params.deployUrl,
                description:   params.description,
                environmentId: params.environmentId,
                gitUrl:        params.gitUrl,
                name:          params.name,
                status:        params.status,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projects/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_projects_update_update>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | RequestType<typeof auth_auth>
  | Promise<RequestType<typeof auth_auth> | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.49.3)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: RequestType<typeof auth_auth> | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
