# Alert Rules for Hybrid Development Platform
groups:
  - name: hybrid-dev-platform
    rules:
      # High-level service availability
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "{{ $labels.job }} has been down for more than 1 minute."

      # API Response Time
      - alert: HighAPILatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High API latency on {{ $labels.job }}"
          description: "95th percentile latency is {{ $value }}s for {{ $labels.job }}"

      # Error Rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate on {{ $labels.job }}"
          description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.job }}"

      # System Resource Alerts
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is {{ $value }}% on {{ $labels.instance }}"

      - alert: DiskSpaceLow
        expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Disk usage is {{ $value }}% on {{ $labels.instance }}"

      # Database Alerts
      - alert: DatabaseConnectionHigh
        expr: pg_stat_activity_count > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High database connections"
          description: "PostgreSQL has {{ $value }} active connections"

      - alert: DatabaseSlowQueries
        expr: rate(pg_stat_statements_mean_time_ms[5m]) > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow database queries detected"
          description: "Average query time is {{ $value }}ms"

      # Redis Alerts
      - alert: RedisHighMemoryUsage
        expr: (redis_memory_used_bytes / redis_memory_max_bytes) * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Redis high memory usage"
          description: "Redis memory usage is {{ $value }}%"

      # Container Alerts
      - alert: ContainerHighCPU
        expr: rate(container_cpu_usage_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container {{ $labels.name }} high CPU usage"
          description: "Container CPU usage is {{ $value }}%"

      - alert: ContainerHighMemory
        expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container {{ $labels.name }} high memory usage"
          description: "Container memory usage is {{ $value }}%"

      # Application-specific Alerts
      - alert: AIEngineRequestQueueHigh
        expr: ai_engine_request_queue_size > 100
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "AI Engine request queue is high"
          description: "AI Engine has {{ $value }} requests queued"

      - alert: ExecutionEngineContainerLimit
        expr: execution_engine_active_containers > 50
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High number of active containers"
          description: "Execution Engine has {{ $value }} active containers"

      - alert: DeploymentFailureRate
        expr: rate(deployment_failures_total[10m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High deployment failure rate"
          description: "Deployment failure rate is {{ $value }} per second"

      # Security Alerts
      - alert: UnauthorizedAccessAttempts
        expr: rate(http_requests_total{status="401"}[5m]) > 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High rate of unauthorized access attempts"
          description: "{{ $value }} unauthorized requests per second"

      - alert: SecurityScanVulnerabilities
        expr: security_vulnerabilities_high > 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "High severity vulnerabilities detected"
          description: "{{ $value }} high severity vulnerabilities found"

      # Business Metrics
      - alert: UserSessionDropHigh
        expr: rate(user_sessions_ended_total[10m]) / rate(user_sessions_started_total[10m]) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High user session drop rate"
          description: "User session drop rate is {{ $value | humanizePercentage }}"

      - alert: ProjectCreationFailures
        expr: rate(project_creation_failures_total[10m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High project creation failure rate"
          description: "Project creation failure rate is {{ $value }} per second"