# Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"
  - "recording.rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  # Application metrics
  - job_name: 'hybrid-dev-platform-backend'
    static_configs:
      - targets: ['localhost:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'hybrid-dev-platform-frontend'
    static_configs:
      - targets: ['localhost:5173']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # AI Engine metrics
  - job_name: 'ai-engine'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'

  # Execution Engine metrics
  - job_name: 'execution-engine'
    static_configs:
      - targets: ['localhost:8001']
    metrics_path: '/metrics'

  # Template Engine metrics
  - job_name: 'template-engine'
    static_configs:
      - targets: ['localhost:8002']
    metrics_path: '/metrics'

  # Deployment Engine metrics
  - job_name: 'deployment-engine'
    static_configs:
      - targets: ['localhost:8003']
    metrics_path: '/metrics'

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:9187']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']

  # MongoDB
  - job_name: 'mongodb'
    static_configs:
      - targets: ['localhost:9216']

  # Elasticsearch
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['localhost:9114']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093