apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: myco-platform
type: Opaque
stringData:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: myco-platform
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP