apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: myco-platform
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: myco-platform
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: myco-platform
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: backend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ai-engine
  namespace: myco-platform
spec:
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    app: ai-engine
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: execution-engine
  namespace: myco-platform
spec:
  ports:
  - port: 8002
    targetPort: 8002
  selector:
    app: execution-engine
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: template-engine
  namespace: myco-platform
spec:
  ports:
  - port: 8003
    targetPort: 8003
  selector:
    app: template-engine
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: validation-engine
  namespace: myco-platform
spec:
  ports:
  - port: 8004
    targetPort: 8004
  selector:
    app: validation-engine
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: myco-platform
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: myco-platform-ingress
  namespace: myco-platform
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: frontend
  type: LoadBalancer